### ISSUE TITLE
Split website and echemdb

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/website#109]
I suggest splitting the combined website and the echemdb project into two separate repositories. Here are some thoughts:

**echemdb**
* `echemdb` can be a standalone module, which works with other data than that published on the website. 
* The module can have functions to selectively download databases from different sources.
* It needs a generic module that can read any kind of datapackages, with a minimum requirement for the metadata structure, i.e., `echemdb.data.generic` which has similar functionalities to the `database` and `entry` modules in cv (The cv module can inherit from these?)
* `echemdb` should be renamed to `scidb` (or something equally generic)
* `scidb` contains modules that allow working with specific datasets (in our case CVs)
* `scidb` has its own documentation and can be published separately

**website**
* Is specifically designed for certain datasets. Currently only CVs but it will probably be extended by other types of data related to electrochemistry.
* `website` can be renamed to `ecwebsite`

**Comment by saraedum** [comment]
We started work on this. There is now the https://github.com/echemdb/echemdb repository. The website does not use it yet thuogh.
