### ISSUE TITLE
Autogenerated pages from new yaml logic

### ISSUE THREAD

**Issue by nicohoermann** [echemdb/website#12]
Until now autogenerated pages expect some important metadataentries in the highest json hierarchie level, to query fast e.g. material.

I will adapt this to the current yaml standard to see if/how we can autogenerate pages from new yaml logic

**Comment by saraedum** [comment]
We don't create datapackage with the .csv and .json yet. We should add this to the GitHub workflow when building the webpage. We want these anyway and then we could leave the current process unchanged.

**Comment by DunklesArchipel** [comment]
I will close this. I don't see how it is related to all the changes made to the project.
