### ISSUE TITLE
echemdb.data.cv.database.Database() does not collect bibliography

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/website#121]
The bibliography is not downloaded when the database is built from gh-pages. The following example returns an empty bibliography

```python
from echemdb.data.cv.database import Database
db = Database()
db.bibliography
```

This is because the BIB files are not copied from `literature` folder into the corresponding folders in `website/generated/svgdigitizer` when the JSON and CSV files are created during the digitization process. The downloaded zip file does not contain any BIB files.

**Comment by saraedum** [comment]
Is there no test for this? We should probably add one then.

I guess the fix then is to add some `cp` command close to here: https://github.com/echemdb/website/blob/main/.github/workflows/build.yml#L37
