### ISSUE TITLE
Bloated repository history

### ISSUE THREAD

**Issue by saraedum** [echemdb/website#141]
Currently, the .git directory has 111MB whereas the actual content of the main branch is only about 3M. Most likely, we added a few binary generated files at some point and removed them again. However, these big files are in the history of the repository and need to be downloaded whenever we clone the repository.

Afaik there is no great way to fix it. The best is probably to break the history of the repository by removing the problematic bits from the repository. It's unclear to me how badly this affects the functionality of the git repository as a whole.

**Comment by DunklesArchipel** [comment]
@saraedum I guess this has bee addressed in #148 and can be closed?

**Comment by saraedum** [comment]
Indeed.
