### ISSUE TITLE
Fix autogenerated relative links

### ISSUE THREAD

**Issue by saraedum** [echemdb/website#4]
Links in MarkDown should be relative so that the website can work from a subdirectory such as `/website/`. When rendering relative links, we need to know at which level of the directory tree we are. However, currently, link rendering is done with statements such as `return f'[{ln}](../../../{filename})'`. This does not work everywhere since it makes an assumption on where the current document is relative to the root. We should probably add a macro such as `{{ relativize(filename) }}` that takes into account the current document path (exposed by mkdocs-macros) and renders a relative link from there.

**Comment by nicohoermann** [comment]
I agree, current way is not working and non-optimal.

**Comment by nicohoermann** [comment]
I fixed it on my local repo, not sure if it works online. See pull request

**Comment by saraedum** [comment]
At the moment, this is not an issue anymore.
