### ISSUE TITLE
Fix data bugs in literature and SVG Files

### ISSUE THREAD

**Issue by saraedum** [echemdb/website#90]
some entries, e.g., https://github.com/echemdb/website/blob/main/literature/jovic_1999_cyclic_247/jovic_1999_cyclic_247_p3_4.yaml#L57 seem to be incomplete.

We should probably add some proper input validation with a schema if we think that schema is now mostly stable.

----
Fix the following issues in all files:
**YAML**  
* Components
   * Are the entries complete
   * Use commonly used names "HClO4" instead of "perchloric acid" unless it is a more complex organic molecule such as pyridine
   * Concentration available
   * In the field `type` use: acid, base, salt, solvent (replace alkaline with base)
* Linked measurements should be nested as 'techniques` in source unless another measurement is directly linked to the shown CV
* electrolyte concentration: Use `mol / l` as unit instead of `M` (only relevant for thos under revision)

**SVG**  
* make sure the units on y1, y2, etc are compliant with astropy units (required for https://github.com/echemdb/svgdigitizer/issues/95)

**Still under revision:**  
- [x] #51 
- [x] #52 
- [x] #53 
- [x] #58 (SVG not yet checked)
- [x] #80 
- [x] #82 
- [x] #91 

Already included literature
- [x] alves_2011_electrochemistry_6010
- [x] briega-martos_2021_cation_XXX
- [x] endo_1999_in-situ_19
- [x] engstfeld_2018_polycrystalline_17743
- [x] gomez-marin_2012_surface_558
- [x] hamad_2003_electrosorption_211
- [x] horswell_2004_a_10970
- [x] jovic_1999_cyclic_247
- [x] kerner_2002_measurement_2055
- [x] li_2000_chronocoulometric_95
- [x] nakamura_2011_structure_165433
- [x] nakamura_2014_structural_22136
- [x] pajkossy_1996_impedance_209
- [x] pajkossy_2001_double_3063
- [x] rehim_1998_electrochemical_1103
- [x] shi_1996_chloride_225
- [x] zei_1991_the_295

**Batch fixing (when all files are merged)**

- [x] YAML:  Remove all comments (Except for that at the top of document - see below)
- [x] YAML: Remove all empty entries (recursively)
- [x] YAML: Add a comment at the very top that states:
    - [x] This is part of the EchemDB.
    - [x] Link to our homepage.
    - [x] Link to example YAML. (ommited)
- [x] SVG: replace `mV/s` to `mV / s`
- [x] move `comment` and `simultaneous measurement` to SVG file
- [x] always include `f` in the filenames to designate the figure
- [x] Add `https://doi.org/` to entry doi 
- [x] Add `https://www.` to entry url
- [x] Add `version: 1` to all yaml files.
- [x] Change DOI to URL
- [x] Remove `figure description` from YAML (these information are now included in the SVG)
- [x] Link curve with curve label in SVG where necessary when the following message appears during digitization with svgdigitizer ![image](https://user-images.githubusercontent.com/39313137/149916719-183b6a0c-1045-4bb1-9d6d-eb40dfb28981.png)
- [x] Change `source.bib` to `source.citation_key`
- [x] Change curator to curation

 
**Finalize**
- [x] Batch Fix all issues
- [x] Fix doctests which include alves and engstfeld
- [x] Fix URL and DOI in `cv_entry.md`

**Comment by DunklesArchipel** [comment]
Overall #102 Addresses the majority and most critical issues.

Some entries might have to be adapted. For example, often the purity of the electrolyte components is nested under `source` instead of `grade`.
