### ISSUE TITLE
Properly render molarity in the title entry with appropriate number of digits.

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/website#99]
In some cases, the molarity of the chemicals is rendered with too many digits. ([Example page](https://echemdb.github.io/website/cv/entries/kerner_2002_measurement_2055_p5_6a_2/))

![image](https://user-images.githubusercontent.com/39313137/148053367-31389b80-8a21-4792-bd2d-88e5f8297a22.png)

**Comment by saraedum** [comment]
What's appropriate though? Should it say `0.2 mM` instead?

**Comment by DunklesArchipel** [comment]
Sorry that I did not provide any useful solution.
In principle, yes, but it might be confusing if it is written `0.1 M XX + 0.2 mM YY`. 
Probably, we should simply use the unit from the JSON.
 
More important would be stripping off these digits after the `2` which do not exist in the input file.
[see here](https://github.com/echemdb/website/blob/main/literature/kerner_2002_measurement_2055/kerner_2002_measurement_2055_p5_6a_2.yaml)
